### PR TITLE
Fix timing attack by using hash_equals() to compare hashes

### LINKED ISSUE #20: RequestAuthenticator.php and ResponseAuthenticator.php are vulnerable to timing attacks
In both files equals operators are used to test the expected hmac against the calculated hmac.
This makes the check susceptible to timing attacks.

Instead you should use: hash_equals(hmac1, hmac2) - available since PHP 5.6

### PR DESCRIPTION
**Pull request by itafroma**
Since we're currently still supporting PHP 5.5, we need to use a polyfill.

Resolves #20.

### CODE REVIEW

File: src/RequestAuthenticator.php [hunk 1]
```diff
@@ -71,7 +71,7 @@ public function authenticate(RequestInterface $request)
         $compareSignature = $compareAuthHeader->getSignature();
 
 
-        if ($signature !== $compareSignature) {
+        if (!hash_equals($signature, $compareSignature)) {
```
Comment (smatyas) [inline src/RequestAuthenticator.php]: Please double check the parameter order here, and at the other use of this function, I think it's incorrect now, but I might be wrong.
As the PHP doc says: "It is important to provide the user-supplied string as the second parameter, rather than the first."

Comment (itafroma) [inline src/RequestAuthenticator.php]: Looks like it's not a problem currently; the implementor added that to ensure forward compatibility in case the function implementation changed in the future: http://stackoverflow.com/a/27912885 But I've gone ahead and fixed it. Thanks!
